# Generated by Django 4.1.7 on 2023-03-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='last_feed_time',
            field=models.DateTimeField(auto_now_add=True, null = True),
        ),
    ]
