# Generated by Django 4.1.7 on 2023-03-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_last_feed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='last_feed_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
