# Generated by Django 4.1.7 on 2023-03-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_animal_last_feed_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='id',
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
