# Generated by Django 4.1.7 on 2023-03-06 00:02

from django.db import migrations, models
import sheriff_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('store_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200, validators=[sheriff_app.validators.validate_first_name])),
                ('last_name', models.CharField(max_length=200, validators=[sheriff_app.validators.validate_last_name])),
                ('phone', models.CharField(max_length=10, validators=[sheriff_app.validators.validate_phone])),
                ('email', models.CharField(max_length=200, validators=[sheriff_app.validators.validate_email])),
            ],
        ),
    ]
