# Generated by Django 4.1.7 on 2023-03-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheriff_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
